import { describe, it, expect } from 'vitest';
import { MAP_NODES, MAP_EDGES, nodeById } from './map';
import { MAIN_QUEST } from './chapters';
import { generateItems, getCategories } from './data';
import rawMap from './map.json';
import type { GameMode } from './hooks/useGameState';

// These guards protect future iterations: when you edit map.json (append a node
// or fork, move a marker), a typo'd id, an invalid mode, or an x/y out of range
// fails here — and map.ts's load-time validate() throws — instead of rendering a
// dead node at runtime.

const VALID_MODES: GameMode[] = ['article', 'case-single', 'case-detect', 'plural', 'story'];
const VALID_CASE_FILTERS = ['all', 'nom', 'akk', 'dat', 'gen'];

describe('map.json source', () => {
    it('the JSON parses into { nodes, edges } and the loader exposes them', () => {
        // map.json is the authored source; map.ts loads + validates it. If the
        // file shape drifts (someone renames `nodes`, breaks the JSON), this and
        // the load-time validate() catch it.
        expect(Array.isArray(rawMap.nodes)).toBe(true);
        expect(Array.isArray(rawMap.edges)).toBe(true);
        expect(MAP_NODES.length).toBe(rawMap.nodes.length);
        expect(MAP_EDGES.length).toBe(rawMap.edges.length);
    });
});

describe('map nodes', () => {
    it('every node launches a valid GameMode', () => {
        for (const node of MAP_NODES) {
            expect(VALID_MODES).toContain(node.mode);
        }
    });

    it('node ids are unique', () => {
        const ids = MAP_NODES.map(n => n.id);
        expect(new Set(ids).size).toBe(ids.length);
    });

    it('positions are within the [0,100] canvas', () => {
        for (const node of MAP_NODES) {
            expect(node.x).toBeGreaterThanOrEqual(0);
            expect(node.x).toBeLessThanOrEqual(100);
            expect(node.y).toBeGreaterThanOrEqual(0);
            expect(node.y).toBeLessThanOrEqual(100);
        }
    });

    it('any preset caseFilter is a valid value', () => {
        for (const node of MAP_NODES) {
            if (node.caseFilter !== undefined) {
                expect(VALID_CASE_FILTERS).toContain(node.caseFilter);
            }
        }
    });

    it('any vocabulary filter references a real, non-empty category', () => {
        // A side quest labelled "Tiere" must actually drill Animals. Guard against
        // a node.filter that points at a category with no nouns (the bug where the
        // label and the played content drifted apart). 'all'/by-rule pass through.
        const categories = new Set(getCategories());
        const items = generateItems();
        for (const node of MAP_NODES) {
            const f = node.filter;
            if (f === undefined || f === 'all' || f === 'by-rule' || f === 'without-rule') continue;
            expect(categories, `node "${node.id}" filter "${f}" is not a category`).toContain(f);
            const inCat = items.filter(i => i.category === f).length;
            expect(inCat, `category "${f}" has no nouns to drill`).toBeGreaterThan(0);
        }
    });

    it('every node carries a non-empty label and icon', () => {
        for (const node of MAP_NODES) {
            expect(node.label.length).toBeGreaterThan(0);
            expect(node.icon.length).toBeGreaterThan(0);
        }
    });
});

describe('map edges', () => {
    it('every edge endpoint references an existing node id', () => {
        for (const edge of MAP_EDGES) {
            expect(nodeById(edge.from), `edge.from "${edge.from}"`).toBeDefined();
            expect(nodeById(edge.to), `edge.to "${edge.to}"`).toBeDefined();
        }
    });

    it('every edge kind is main or fork', () => {
        for (const edge of MAP_EDGES) {
            expect(['main', 'fork']).toContain(edge.kind);
        }
    });

    it('no edge is a self-loop', () => {
        for (const edge of MAP_EDGES) {
            expect(edge.from).not.toBe(edge.to);
        }
    });
});

// The map is now GENERATED by scripts/author.ts to match the chapters it produced,
// so these are STRUCTURAL invariants — true for any generated graph — not literal
// node lists. (CLAUDE.md's rule for generated/random output: test invariants, not
// exact output.) A specific node set would break on every regeneration.
describe('generated map graph', () => {
    it('has at least one node and one chapter node', () => {
        expect(MAP_NODES.length).toBeGreaterThan(0);
        const chapterNodes = MAP_NODES.filter(n => n.chapterId);
        expect(chapterNodes.length, 'a map must launch at least one chapter').toBeGreaterThan(0);
    });

    it('every node is reachable from the first node via edges', () => {
        // The graph root is the first node (the main quest's opening chapter).
        const reachable = new Set<string>([MAP_NODES[0].id]);
        // Fixed-point over the (small) edge set.
        let grew = true;
        while (grew) {
            grew = false;
            for (const edge of MAP_EDGES) {
                if (reachable.has(edge.from) && !reachable.has(edge.to)) {
                    reachable.add(edge.to);
                    grew = true;
                }
            }
        }
        for (const node of MAP_NODES) {
            expect(reachable.has(node.id), `node "${node.id}" unreachable`).toBe(true);
        }
    });

    it('every chapter node rides mode:story and points at a real MAIN_QUEST chapter', () => {
        const questIds = new Set(MAIN_QUEST.map(c => c.id));
        const chapterNodes = MAP_NODES.filter(n => n.chapterId);
        for (const n of chapterNodes) {
            expect(n.mode, `${n.id} must ride mode:story`).toBe('story');
            expect(questIds.has(n.chapterId!), `chapterId "${n.chapterId}" must exist`).toBe(true);
        }
    });

    it('non-chapter nodes (side quests) hang off the graph via a fork edge', () => {
        // Every node that isn't a chapter is a side quest — it should be entered by
        // a fork, never sit unconnected. (Chapters are linked by main roads.)
        const sideQuests = MAP_NODES.filter(n => !n.chapterId && n.id !== MAP_NODES[0].id);
        for (const sq of sideQuests) {
            const incoming = MAP_EDGES.filter(e => e.to === sq.id);
            expect(incoming.length, `side quest "${sq.id}" has no incoming edge`).toBeGreaterThan(0);
            expect(
                incoming.some(e => e.kind === 'fork'),
                `side quest "${sq.id}" should be entered by a fork`,
            ).toBe(true);
        }
    });

    it('the main-quest road links its chapter nodes in TOC order', () => {
        // Only assert order over the chapters that ACTUALLY have a node on the map
        // (a generated map may ship a subset of MAIN_QUEST). Consecutive mapped
        // chapters must be joined by a 'main' edge.
        const mainEdges = MAP_EDGES.filter(e => e.kind === 'main');
        const nodeForChapter = (cid: string) => MAP_NODES.find(n => n.chapterId === cid);
        const mappedInOrder = MAIN_QUEST.map(c => c.id).filter(cid => nodeForChapter(cid));
        for (let i = 0; i < mappedInOrder.length - 1; i++) {
            const a = nodeForChapter(mappedInOrder[i])!.id;
            const b = nodeForChapter(mappedInOrder[i + 1])!.id;
            expect(
                mainEdges.some(e => e.from === a && e.to === b),
                `main road should link ${a} → ${b}`,
            ).toBe(true);
        }
    });
});
